\COPY Users FROM 'data/Users.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Category FROM 'data/Category.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Product FROM 'data/Product.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Buyer FROM 'data/Buyer.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Seller FROM 'data/Seller.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Selling FROM 'data/Selling.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Cart FROM 'data/Cart.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Orders FROM 'data/Orders.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Message FROM 'data/Message.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Product_Review FROM 'data/Product_Review.csv' WITH DELIMITER ',' NULL '' CSV
\COPY Seller_Review FROM 'data/Seller_Review.csv' WITH DELIMITER ',' NULL '' CSV
